### ISSUE TITLE
The image build locally can not work!

### ISSUE THREAD

**Issue by Raid57** [BoCloud/JobFlow#19]
![image](https://user-images.githubusercontent.com/91405051/185338283-4b6201e8-e1bc-42cb-b38b-e61ac50142a9.png)

**Comment by Raid57** [comment]
I followed the official markdown document, but i do not know the reason causing this problem.

**Comment by zhoumingcheng** [comment]
![ZTUD)_LZ~9X7O{I%BUZLG(1](https://user-images.githubusercontent.com/52434045/185346935-d656df7d-7bde-4fa9-9b93-0ac42b8ec016.png)
Tried your process but didn't get the same result. can you provide more information

**Comment by zhoumingcheng** [comment]
> ![ZTUD)_LZ~9X7O{I%BUZLG(1](https://user-images.githubusercontent.com/52434045/185346935-d656df7d-7bde-4fa9-9b93-0ac42b8ec016.png)
> Tried your process but didn't get the same result. can you provide more information

Tried your process but didn't get the same result. can you provide more information
![ZTUD)_LZ~9X7O{I%BUZLG(1](https://user-images.githubusercontent.com/52434045/185347293-bd4f9488-4232-4b3e-9ac3-554d2c91cca4.png)

**Comment by zhoumingcheng** [comment]
> I followed the official markdown document, but i do not know the reason causing this problem.

![ZTUD)_LZ~9X7O{I%BUZLG(1](https://user-images.githubusercontent.com/52434045/185347342-e423e1cf-3717-4a3f-b2de-260d610238dc.png)
Tried your process but didn't get the same result. can you provide more information

**Comment by renwenlong-github** [comment]
![image](https://user-images.githubusercontent.com/33648707/185353113-5dfd9170-4620-4f6f-8bf8-eb1efe2c1963.png)
I got the same error,I guess you should delete the image, and try again

**Comment by Raid57** [comment]
![image](https://user-images.githubusercontent.com/91405051/185382276-8507e4a0-389e-4061-ace7-f270e936b90e.png)

**Comment by Raid57** [comment]
> > I followed the official markdown document, but i do not know the reason causing this problem.
> 
> ![ZTUD)_LZ~9X7O{I%BUZLG(1](https://user-images.githubusercontent.com/52434045/185347342-e423e1cf-3717-4a3f-b2de-260d610238dc.png) Tried your process but didn't get the same result. can you provide more information

Could u push this image to dockerhub, and i pull it for testing?

**Comment by zhoumingcheng** [comment]
> > > I followed the official markdown document, but i do not know the reason causing this problem.
> > 
> > 
> > ![ZTUD)_LZ~9X7O{I%BUZLG(1](https://user-images.githubusercontent.com/52434045/185347342-e423e1cf-3717-4a3f-b2de-260d610238dc.png) Tried your process but didn't get the same result. can you provide more information
> 
> Could u push this image to dockerhub, and i pull it for testing?

The current situation is normal, because the manager needs to specify kubeconfig to start and the corresponding kubeconfig is not specified here

**Comment by Raid57** [comment]
> 
![image](https://user-images.githubusercontent.com/91405051/185384998-3b84a77b-218f-47b2-a3be-d6b3a5be6c79.png)
got it, but when i `kubectl apply /Jobflow/deploy/jobflow.yaml`, the jobflow-controller pod meets problem of "Back-off restarting failed container", and then i logs the pod, showed error of the last line in the picture.

**Comment by zhoumingcheng** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/91405051/185384998-3b84a77b-218f-47b2-a3be-d6b3a5be6c79.png) got it, but when i `kubectl apply /Jobflow/deploy/jobflow.yaml`, the jobflow-controller pod meets problem of "Back-off restarting failed container", and then i logs the pod, showed error of the last line in the picture.

Since the alpine base image is used here, the manager needs to be statically compiled. You need to set go env CGO_ENABLED="0".The above are all caused by not using static compilation.

**Comment by zhoumingcheng** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/91405051/185384998-3b84a77b-218f-47b2-a3be-d6b3a5be6c79.png) got it, but when i `kubectl apply /Jobflow/deploy/jobflow.yaml`, the jobflow-controller pod meets problem of "Back-off restarting failed container", and then i logs the pod, showed error of the last line in the picture.

I will add these in the makefile, thanks

**Comment by Raid57** [comment]
> thanks for your help, and after u update the makefile, can u let me know and i can re-pull it again! Thanks a lot

**Comment by HecarimV** [comment]
@huangyufeng0507 you can retry now, thanks for your feedback.

**Comment by renwenlong-github** [comment]
> ![图片](https://user-images.githubusercontent.com/91405051/185338283-4b6201e8-e1bc-42cb-b38b-e61ac50142a9.png)

first, you shold make build the project and prodect  bin/manager file , then docker build it
