### ISSUE TITLE
How to use jobflow to depend on the status of a job in the previous task？

### ISSUE THREAD

**Issue by Trainbow** [BoCloud/JobFlow#21]
Hi, I used jobflow to build a tensorflow-ps-workers task, and when the tensorflow distributed training finished. The ps-job will be terminated and the workers were succeed. But the jobflow can not start the next job which depends on the previous whole task job. It looks like the jobflow was affected by the state of ps-job.
So, I want to know how to start the next job with the one of the whole task(such as the completed worker-job)?
Hope to reply soon, thanks!

**Comment by hwdef** [comment]
Simply put, if job b depends on job a, then when job a is completed, job b will run

**Comment by Trainbow** [comment]
已收到，谢谢！

**Comment by Trainbow** [comment]
![image](https://user-images.githubusercontent.com/26664964/185882507-5696bb29-999b-4bcc-b601-16eb8ddedbdb.png)
yes, I know what you means. Just like this, when the download succeed, the ps and worker job will run.
But when I fininshed train the tensorflow model, the ps will terminated, leave the two workers and their status are succeeded. But the next job depends on the training task cannot run automatically.
![image](https://user-images.githubusercontent.com/26664964/185883375-a0c16f2a-433a-455a-8110-75dca29cce0e.png)
This is my define jobflow yaml:
-------------------

apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: tensorflow-dist
  namespace: test
spec:
  jobRetainPolicy: delete
  flows:
    - name: download
      dependsOn:
        targets: []
    - name: task-train
      dependsOn:
        targets: ['download']
    - name: upload
      dependsOn:
        targets: ['task-train']

**Comment by hwdef** [comment]
Are you saying that the `upload` task didn't run properly after the `task-train` completed?

**Comment by Trainbow** [comment]
yes，the task-train can run immediately，but the upload can not.

**Comment by hwdef** [comment]
Can you provide more information, what is the status of jobflow

**Comment by Trainbow** [comment]
![image](https://user-images.githubusercontent.com/26664964/185893691-e2ea2d2e-b393-45d4-96ca-52ace041473e.png)

It seems to keep looping. Is it possible to add a field to specify to probe the status of a completed pod to start subsequent work?

**Comment by Trainbow** [comment]
![image](https://user-images.githubusercontent.com/26664964/185894264-3ea69144-7128-48c5-b2ff-74faba88cb63.png)

the jobflow is pending, I think maybe the ps's pod was terminated by the whole task-train, and jobflow can not get the succeed status?

**Comment by hwdef** [comment]
please run `kubectl describe jobflow tensorflow-dist`

**Comment by Trainbow** [comment]
![image](https://user-images.githubusercontent.com/26664964/185896051-2be4c923-6753-4977-a92e-5e3f3e36ea9e.png)
this is the moment when finished the tensorflow-task.
----------------------------
this is the information:

Name:         tensorflow-dist
Namespace:    test
Labels:       <none>
Annotations:  <none>
API Version:  flow.volcano.sh/v1alpha1
Kind:         JobFlow
Metadata:
  Creation Timestamp:  2022-08-22T10:01:36Z
  Generation:          1
  Managed Fields:
    API Version:  flow.volcano.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:jobRetainPolicy:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-08-22T10:01:36Z
    API Version:  flow.volcano.sh/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:flows:
      f:status:
        .:
        f:state:
          .:
          f:phase:
    Manager:         manager
    Operation:       Update
    Time:            2022-08-22T10:01:37Z
  Resource Version:  74677043
  Self Link:         /apis/flow.volcano.sh/v1alpha1/namespaces/test/jobflows/tensorflow-dist
  UID:               399b9641-31d7-417e-8368-4a6324b3d2e3
Spec:
  Flows:
    Depends On:
      Targets:
    Name:  minio-download
    Depends On:
      Targets:
        minio-download
    Name:  task-model
    Depends On:
      Targets:
        task-model
        minio-download
    Name:             minio-upload
  Job Retain Policy:  retain
Status:
  State:
    Phase:  Pending
Events:
  Type    Reason   Age    From                     Message
  ----    ------   ----   ----                     -------
  Normal  Created  5m35s  containerset-controller  create a job named tensorflow-dist-minio-download!
  Normal  Created  5m11s  containerset-controller  create a job named tensorflow-dist-task-model!
  Normal  Created  2m26s  containerset-controller  create a job named tensorflow-dist-minio-upload!


It seems try to create the job, but I can't find it.

**Comment by hwdef** [comment]
Can you send your yaml, I will test it on my own environment

**Comment by zhoumingcheng** [comment]
Can you provide more log information for jobflow-controller

**Comment by HecarimV** [comment]
> It seems try to create the job, but I can't find it.

Let's take a look at the vcjob list (just use `kubectl get vcjob -n test`), upload job may be in pending state

**Comment by Trainbow** [comment]
Wait a moment, I will write another easy example to run. If it has the same problem, I’ll send it out for you to test, thanks a lot.

**Comment by Trainbow** [comment]
Sorry, I got I'm having some network problems and can't connect to the k8s clusters.
I wrote an example like this to observe whether the next job cannot be started due to the shutdown of the ps node of tensorlfow. I will continue testing it in my environment tomorrow.
------------------------

jobFlow.yaml
------------------------
apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: tensorflow-jobflow
  namespace: test
spec:
  jobRetainPolicy: delete   # After jobflow runs, keep the generated job. Otherwise, delete it.
  flows:
    - name: tensorflow-dist-mnist
      dependsOn:
        targets: []
    - name: prints
      dependsOn:
        targets: ['tensorflow-dist-mnist']


jobTemplate.yaml
----------------------------------
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: tensorflow-dist-mnist
  namespace: test
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: []
    env: []
    svc: []
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  maxRetry: 5
  tasks:
    - replicas: 1
      name: ps
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"ps\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: OnFailure
    - replicas: 2
      name: worker
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"worker\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: prints
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "print-pod"
      template:
        metadata:
          name: print
        spec:
          containers:
            - image: busybox:1.30
              command: ["/bin/sh","-c","while true; do echo pod1; sleep 30; done;"]
              imagePullPolicy: IfNotPresent
              name: busybox
          restartPolicy: OnFailure

**Comment by Trainbow** [comment]
Sorry, I got I'm having some network problems and can't connect to the k8s clusters.
I wrote an example like this to observe whether the next job cannot be started due to the shutdown of the ps node of tensorlfow. I will continue testing it in my environment tomorrow.

jobFlow.yaml
`apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
name: tensorflow-jobflow
namespace: test
spec:
jobRetainPolicy: delete # After jobflow runs, keep the generated job. Otherwise, delete it.
flows:
- name: tensorflow-dist-mnist
dependsOn:
targets: []
- name: prints
dependsOn:
targets: ['tensorflow-dist-mnist']`

jobTemplate.yaml
`apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
name: tensorflow-dist-mnist
namespace: test
spec:
minAvailable: 3
schedulerName: volcano
plugins:
ssh: []
env: []
svc: []
policies:
- event: PodEvicted
action: RestartJob
queue: default
maxRetry: 5
tasks:
- replicas: 1
name: ps
template:
spec:
containers:
- command:
- sh
- -c
- |
PS_HOST=cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
WORKER_HOST=cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
export TF_CONFIG={"cluster":{"ps":[${PS_HOST}],"worker":[${WORKER_HOST}]},"task":{"type":"ps","index":${VK_TASK_INDEX}},"environment":"cloud"};
python /var/tf_dist_mnist/dist_mnist.py
image: volcanosh/dist-mnist-tf-example:0.0.1
name: tensorflow
ports:
- containerPort: 2222
name: tfjob-port
resources: {}
restartPolicy: OnFailure
- replicas: 2
name: worker
policies:
- event: TaskCompleted
action: CompleteJob
template:
spec:
containers:
- command:
- sh
- -c
- |
PS_HOST=cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
WORKER_HOST=cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
export TF_CONFIG={"cluster":{"ps":[${PS_HOST}],"worker":[${WORKER_HOST}]},"task":{"type":"worker","index":${VK_TASK_INDEX}},"environment":"cloud"};
python /var/tf_dist_mnist/dist_mnist.py
image: volcanosh/dist-mnist-tf-example:0.0.1
name: tensorflow
ports:
- containerPort: 2222
name: tfjob-port
resources: {}
restartPolicy: OnFailure
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
name: prints
spec:
minAvailable: 1
schedulerName: volcano
priorityClassName: high-priority
policies:
- event: PodEvicted
action: RestartJob
plugins:
ssh: []
env: []
svc: []
maxRetry: 5
queue: default
tasks:
- replicas: 1
name: "print-pod"
template:
metadata:
name: print
spec:
containers:
- image: busybox:1.30
command: ["/bin/sh","-c","while true; do echo pod1; sleep 30; done;"]
imagePullPolicy: IfNotPresent
name: busybox
restartPolicy: OnFailure`

**Comment by Trainbow** [comment]
Sorry, I got I'm having some network problems and can't connect to the k8s clusters.
I wrote an example like this to observe whether the next job cannot be started due to the shutdown of the ps node of tensorlfow. I will continue testing it in my environment tomorrow.

jobFlow.yaml
`apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
name: tensorflow-jobflow
namespace: test
spec:
jobRetainPolicy: delete # After jobflow runs, keep the generated job. Otherwise, delete it.
flows:
- name: tensorflow-dist-mnist
dependsOn:
targets: []
- name: prints
dependsOn:
targets: ['tensorflow-dist-mnist']`


jobTemplate.yaml
`apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
name: tensorflow-dist-mnist
namespace: test
spec:
minAvailable: 3
schedulerName: volcano
plugins:
ssh: []
env: []
svc: []
policies:
- event: PodEvicted
action: RestartJob
queue: default
maxRetry: 5
tasks:
- replicas: 1
name: ps
template:
spec:
containers:
- command:
- sh
- -c
- |
PS_HOST=cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
WORKER_HOST=cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
export TF_CONFIG={"cluster":{"ps":[${PS_HOST}],"worker":[${WORKER_HOST}]},"task":{"type":"ps","index":${VK_TASK_INDEX}},"environment":"cloud"};
python /var/tf_dist_mnist/dist_mnist.py
image: volcanosh/dist-mnist-tf-example:0.0.1
name: tensorflow
ports:
- containerPort: 2222
name: tfjob-port
resources: {}
restartPolicy: OnFailure
- replicas: 2
name: worker
policies:
- event: TaskCompleted
action: CompleteJob
template:
spec:
containers:
- command:
- sh
- -c
- |
PS_HOST=cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
WORKER_HOST=cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ",";
export TF_CONFIG={"cluster":{"ps":[${PS_HOST}],"worker":[${WORKER_HOST}]},"task":{"type":"worker","index":${VK_TASK_INDEX}},"environment":"cloud"};
python /var/tf_dist_mnist/dist_mnist.py
image: volcanosh/dist-mnist-tf-example:0.0.1
name: tensorflow
ports:
- containerPort: 2222
name: tfjob-port
resources: {}
restartPolicy: OnFailure
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
name: prints
spec:
minAvailable: 1
schedulerName: volcano
priorityClassName: high-priority
policies:
- event: PodEvicted
action: RestartJob
plugins:
ssh: []
env: []
svc: []
maxRetry: 5
queue: default
tasks:
- replicas: 1
name: "print-pod"
template:
metadata:
name: print
spec:
containers:
- image: busybox:1.30
command: ["/bin/sh","-c","while true; do echo pod1; sleep 30; done;"]
imagePullPolicy: IfNotPresent
name: busybox
restartPolicy: OnFailure`

**Comment by Trainbow** [comment]
Sorry, I encountered some network problems, I can't connect to the k8s server at the moment. I wrote a simple example to verify whether the ps node exit of tensorflow caused jobflow to fail to start the next task. I will test it tomorrow.

JobFlow.yaml

apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: tensorflow-jobflow
  namespace: test
spec:
  jobRetainPolicy: delete   # After jobflow runs, keep the generated job. Otherwise, delete it.
  flows:
    - name: tensorflow-dist-mnist
      dependsOn:
        targets: []
    - name: prints
      dependsOn:
        targets: ['tensorflow-dist-mnist']

JobTemplate.yaml

apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: tensorflow-dist-mnist
  namespace: test
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: []
    env: []
    svc: []
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  maxRetry: 5
  tasks:
    - replicas: 1
      name: ps
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"ps\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: OnFailure
    - replicas: 2
      name: worker
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"worker\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: prints
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "print-pod"
      template:
        metadata:
          name: print
        spec:
          containers:
            - image: busybox:1.30
              command: ["/bin/sh","-c","while true; do echo pod1; sleep 30; done;"]
              imagePullPolicy: IfNotPresent
              name: busybox
          restartPolicy: OnFailure

**Comment by Trainbow** [comment]
Sorry, I encountered some network problems, I can't connect to the k8s server at the moment. I wrote a simple example to verify whether the ps node exit of tensorflow caused jobflow to fail to start the next task. I will test it tomorrow and get back to you.

**Comment by Trainbow** [comment]
jobflow.yaml

apiVersion: flow.volcano.sh/v1alpha1
kind: JobFlow
metadata:
  name: tf-test
  namespace: test
spec:
  jobRetainPolicy: delete   # After jobflow runs, keep the generated job. Otherwise, delete it.
  flows:
    - name: prints
      dependsOn:
        targets: []
    - name: tensorflow-dist-mnist
      dependsOn:
        targets: ['prints']
    - name: prints-2
      dependsOn:
        targets: ['tensorflow-dist-mnist']

jobTemplate.yaml

apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: tensorflow-dist-mnist
  namespace: test
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: []
    env: []
    svc: []
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  maxRetry: 5
  tasks:
    - replicas: 1
      name: ps
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"ps\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: OnFailure
    - replicas: 2
      name: worker
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"worker\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: prints
  namespace: test
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "print-pod"
      template:
        metadata:
          name: print
        spec:
          containers:
            - image: busybox:1.30
              command: ["/bin/sh","-c","echo pod-1; sleep 10;"]
              imagePullPolicy: IfNotPresent
              name: busybox
          restartPolicy: OnFailure
---
apiVersion: flow.volcano.sh/v1alpha1
kind: JobTemplate
metadata:
  name: prints-2
  namespace: test
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 1
      name: "p2"
      template:
        metadata:
          name: print
        spec:
          containers:
            - image: busybox:1.30
              command: ["/bin/sh","-c","echo pod-2; sleep 10;"]
              imagePullPolicy: IfNotPresent
              name: busybox
          restartPolicy: OnFailure


This time the tensorflow-task cannot start...

**Comment by Trainbow** [comment]
[JobFlow.md](https://github.com/BoCloud/JobFlow/files/9398587/JobFlow.md)

This time the tensorflow-task cannot start, I don't know why...

**Comment by Trainbow** [comment]
![image](https://user-images.githubusercontent.com/26664964/186048081-bc11b7d8-21bc-43b8-8116-f25efe9f8231.png)

I used `kubectl get vcjob -n test` and find the next job has created but not start and cannot describe

**Comment by HecarimV** [comment]
![image](https://user-images.githubusercontent.com/38995829/186063137-a7a6b8eb-1c9e-4697-b55f-b93e2c83edd4.png)
I haven't been able to reproduce the problem, maybe you can use vcjob to run the tensorflow job alone to see if it can start

**Comment by Trainbow** [comment]
> 

Could you tell me your jobflow and volcano version, I think it might be the problem that I have been using volcano1.5.1?
![image](https://user-images.githubusercontent.com/26664964/186064031-5ca1ae1d-7dd4-4b06-a8fb-1f61084111e1.png)

![image](https://user-images.githubusercontent.com/26664964/186064065-82e46d9f-a542-49ab-92db-92715fcc04fe.png)

**Comment by HecarimV** [comment]
volcano: v1.6.0
jobflow: v0.0.1 (build from the lastest code)

**Comment by Trainbow** [comment]
I test the example in my local environment and it works, thanks.
I think it's k8s environment's problem.

**Comment by Trainbow** [comment]
已收到，谢谢！
